package com.kronostt.service.mapper;

import com.kronostt.engine.model.Session;
import com.kronostt.persistence.entity.SessionEntity;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingConstants;

@Mapper(config = GlobalMapperConfig.class, componentModel = MappingConstants.ComponentModel.SPRING, uses = {TeacherMapper.class, BatchMapper.class, RoomMapper.class, SubjectMapper.class})
public interface SessionMapper {

    Session toEngine(SessionEntity entity);

    /**
     * Maps a transient engine POJO to a new database entity.
     * Note: ID and Job are ignored as they are generated by the DB
     * and set by the Service layer respectively. This method should
     * ONLY be used for initial creation, never for updating.
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "job", ignore = true)
    SessionEntity toEntity(Session pojo);
}
