# --- APPLICATION INFO ---
spring.application.name=kronostt-engine
# --- ACTIVE PROFILE ---
# Change this to 'prod' when deploying, or pass -Dspring.profiles.active=prod via command line
spring.profiles.active=prod
# --- JACKSON (JSON PARSING) ADD-ONS ---
# Prevents crashing if the frontend sends an empty JSON object
spring.jackson.serialization.fail-on-empty-beans=false
# Converts camelCase DTOs to snake_case in JSON (Optional, but common in enterprise APIs)
# spring.jackson.property-naming-strategy=SNAKE_CASE
# --- GLOBAL LOGGING ---
logging.level.root=INFO
logging.level.com.kronostt=INFO
spring.jpa.open-in-view=true